// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssjomyrovejejsjcffdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzam9teXJvdmVqZWpzamNmZmRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMDAxNzksImV4cCI6MjA2NDY3NjE3OX0.uUbJ6MjtAInByS3X3m90qm5EFb4Ov3W9ODRGvvvGqIM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);